stages:
  - test
  - release
.go_template_defaults:
  stage: test
.semver_template_defaults:
  stage: release
variables:
  SEMVER_PREFIX: v
include:
  - { project: bonsai-oss/organization/automate/ci-templates, file: templates/language/go.yml, ref: 1.0.5 }
  - { project: bonsai-oss/organization/automate/ci-templates, file: templates/release/semver.yml, ref: 1.0.5 }
