version: 1

project_name: testfmt

release:
  draft: false
  prerelease: auto
  github:
    owner: bonsai-oss
    name: testfmt
  name_template: 'Release {{.Tag}}'

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

archives:
  - format: binary

nfpms:
  - id: testfmt
    maintainer: bonsai-oss
    homepage: https://github.com/bonsai-oss/testfmt
    file_name_template: '{{ .ProjectName }}_{{ replace .Version "v" "" }}_{{ .Os }}_{{ .Arch }}'
    formats:
      - deb
